### ISSUE TITLE
FATAL ERROR in input BAM file

### ISSUE THREAD

**Issue by ChiaraF32** [AnkurJainLab/SATCfinder#1]
Hi,

I am having an issue with running SATCfinder on the test data provided.

This is a copy of the configurations I have specified in the `SATCfinder.sh` script.

```
#!/bin/bash
set -e                        # Exit immediately on errors
#########################################################################################
##### Configure these variables for your datasets.
#########################################################################################
datasetPrefix=HEK-test        # Name this dataset
repeatType="CAG"              # Define your repeat type. Degenerate IUPAC bases are OK
minRepeatLength=3             # How many repeats to search & trim?
numCores=4                    # How many cores to run with?
removeTemporaryFiles=false     # Clean up temporary files created by this script? true/false

#Set up some file paths
#Your raw reads, such as the small example dataset
rawRead1=/data/SATCfinder/WT_HEK_1.fq.gz
rawRead2=/data/SATCfinder/WT_HEK_2.fq.gz
#The output directory. This will be made if it does not exist
outputDir=./testSATCfinder

#Your STAR genome directory
genomeDir=/data/STARIndex #correct version
#If you need a spike-in fasta file, e.g. for mapping to a plasmid, add the path to the fasta file here.
fastaPath=""
#Directory for bbtools (https://sourceforge.net/projects/bbmap/)
bbdukDir=/data/SATCfinder/bbmap
#Directory for SATCfinder scripts. Default: the same directory as this script, but can be changed
SATCfinderDir=/data/SATCfinder
#Directory for STAR executable, if not in $PATH
STARDir=""
#Directory for cutadapt, if not in $PATH
cutadaptDir="/home/ubuntu/.local/bin/"
```

The issue arised during STAR alignment step:

```
07-02-24 04:46:23 INFO : 0 reads (0.0%) had no repeats matching >=3xCAG/CTG
        STAR --genomeDir /data/STARIndex --runThreadN 4 --readFilesCommand zcat --readFilesType SAM PE --readFilesIn ./testSATCfinder/HEK-test.sam.gz --outFileNamePrefix ./testSATCfinder/HEK-test_ --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within
        STAR version: 2.7.10b   compiled: 2023-06-27T04:03:47+00:00 :/data/arriba/STAR-2.7.10b/source
Feb 07 04:46:24 ..... started STAR run
Feb 07 04:46:24 ..... loading genome
^A^[^A^[Feb 07 04:58:01 ..... started mapping

ReadAlignChunk_processChunks.cpp:63:processChunks EXITING because of FATAL ERROR in input BAM file: the consecutive lines in paired-end BAM have wrong mate FLAG bits:
A00738:570:HT5HFDSX5:1:1101:21043:1016:N:0:ACAGTTCGAT+NCGTACAGGT   0   vs   A00738:570:HT5HFDSX5:1:1101:21043:1016:N:0:ACAGTTCGAT+NCGTACAGGT   0

 SOLUTION: fix BAM file formatting. Paired-end reads should be always consecutive lines, with exactly 2 lines per paired-end read. Mate1 should have 0x40 bit set in the FLAG, Mate2 should have 0x80 bit set in the FLAG
Feb 07 04:58:01 ...... FATAL ERROR, exiting
```

I also tried with my own data, but I got the same issue.

Version details:
STAR version `2.7.10b`

**Comment by AnkurJainLab** [comment]
Hi Chiara,

I haven't seen this bug, but it looks like the intermediate SAM file isn't formatted properly after trimming on your system. Could you attach your /testSATCfinder/HEK-test.sam.gz and SATCfinder.sh files here so I can troubleshoot?

Thanks,
Rachel

**Comment by ChiaraF32** [comment]
Hi Rachel, 

Thanks for offering to help.

I have attached the sam file and the run script for reference, as well as the log file of the run. 

Cheers,
Chiara
[SATCfinder.sh.txt](https://github.com/AnkurJainLab/SATCfinder/files/14275860/SATCfinder.sh.txt)
[WT_HEK.sam.gz](https://github.com/AnkurJainLab/SATCfinder/files/14275861/WT_HEK.sam.gz)
[1_test.log.txt](https://github.com/AnkurJainLab/SATCfinder/files/14275865/1_test.log.txt)

**Comment by AnkurJainLab** [comment]
Hi Chiara,

After some testing, I found that your version of STAR requires more stringent SAM flags for read pairs. I've released a new SATCfinder version (0.1.1) which adds mate flags and hopefully fixes your issue.

Thanks,
Rachel

**Comment by ChiaraF32** [comment]
Hi Rachel,

I have pulled the recent updates which have fixed my issue.

Thanks for your help.

--Chiara

**Comment by ChiaraF32** [comment]
Hi Rachel,

I have now run SATCfinder on a sample of my own data but the issue has arisen again.

Please find attached the log file, run script. The sam file is too large to attach.

Sorry if I am missing something obvious.

--Chiara

[SATCfinder_2.sh.txt](https://github.com/AnkurJainLab/SATCfinder/files/14307495/SATCfinder_2.sh.txt)
[2_control.log.txt](https://github.com/AnkurJainLab/SATCfinder/files/14307496/2_control.log.txt)

**Comment by AnkurJainLab** [comment]
Hi Chiara,

Your FASTQ read names have an internal space between the read name and mate suffix, which my scripts weren't handling properly. I've added a new option to fix this. Please fetch the newest version and provide 
--readSuffixDelimiter ' '
(note the space between quotes) as an option to SATCfinder.py during read trimming.

Thanks,
Rachel

**Comment by ChiaraF32** [comment]
Hi Rachel,

Your solution fixed my issue, thank you.

--Chiara
